version: '3'
services:
  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    restart: always
    ports:
      - 26379:26379
    networks: 
      - app
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes: 
      - ./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf
  
  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    restart: always
    ports:
      - 26380:26379
    networks: 
      - app
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes: 
      - ./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf
  
  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    restart: always
    ports:
      - 26381:26379
    networks: 
      - app
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes: 
      - ./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf

networks: 
  app:
    external: true