version: '3'
services:
  # nginx:
  #   image: nginx
  #   restart: always
  #   ports:
  #     - 8888:80
  #     - 8443:443
  #   environment:
  #     - TZ=Asia/Shanghai
  #   volumes:
  #     - ./data/conf/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./data/conf/vhost:/etc/nginx/conf.d
  #     - ./www:/usr/share/nginx/html
  #     - ./data/logs:/var/log/nginx
  nginx_master:
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:80
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./www/index-master.html:/usr/share/nginx/html/index.html
      - ./www/favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./keepalived/master.conf:/etc/keepalived/keepalived.conf
    networks:
      static-network:
        ipv4_address: 172.200.128.2
    cap_add:
      - NET_ADMIN
  
  nginx_slave:
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:80
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./www/index-slave.html:/usr/share/nginx/html/index.html
      - ./www/favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./keepalived/slave.conf:/etc/keepalived/keepalived.conf
    networks:
      static-network:
        ipv4_address: 172.200.128.3
    cap_add:
      - NET_ADMIN
  proxy:
    image:  haproxy
    ports:
      - 8099:6301
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - static-network

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.200.0.0/16
